### ISSUE TITLE
traefik ingress authentication with keycloak gatekeeper on EKS, error: no session found in request

### ISSUE THREAD

**Issue by vishalgoel1988** [int128/kubernetes-dashboard-proxy#10]
HI All,

I am setting up traefik ingress with keycloak gatekeeper authentication for kibana app on EKS. I have deployed keycloak gatekeeper as below:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: keycloak-gatekeeper
  name: keycloak-gatekeeper
  namespace: pulse
spec:
  selector:
    matchLabels:
      component: keycloak-gatekeeper
  replicas: 1
  template:
    metadata:
      labels:
        component: keycloak-gatekeeper
    spec:
      containers:
        - image: keycloak/keycloak-gatekeeper
          imagePullPolicy: Always
          name: keycloak-gatekeeper
          ports:
            - containerPort: 3000
          args:
            - --discovery-url=http://keycloak:8080/auth/realms/realm1 #keycloak is clusterip service over keycloak deployment
            - --secure-cookie=false
            - --enable-default-deny=true
            - --client-id=Vista
            - --client-secret=2f1aa7dd-2aa9-4fd0-956c-5c45b2bf2091
            - --listen=0.0.0.0:3000 # listen on port 3000 on all interfaces
            - --redirection-url=http://127.0.0.1:3000
            - --upstream-url=http://127.0.0.1:5601
            - --enable-logging=true
            - --enable-json-logging=true
            - --verbose=true
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-gatekeeper
  namespace: pulse
  labels:
    component: keycloak-gatekeeper
spec:
  ports:
  - port: 3000
    name: http
  selector:
    component: keycloak-gatekeeper
```

I have traefik ingress as below:
```
#ingress routes for https
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: pulseingressroutetls
  namespace: pulse
spec:
  entryPoints:
    - websecure
  routes:
  - match: PathPrefix(`/kibana`)
    kind: Rule
    services:
    - name: keycloak-gatekeeper
      port: 3000
    middlewares:
      - name: stripprefix
  tls:
    secretName: pulsetlssecret
---
#strip prefix
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: stripprefix
  namespace: pulse
spec:
  stripPrefix:
    prefixes:
      - /kibana
```
My traefik ingress is exposed as ELB service. 
Now, whenever i browse to **https://elb_host/kibana**, it just redirects it **https://elb_host/ouath/authorize?state=<..>** and throws 404.
I expect it to first redirect to keycloak auth url (**https://elb_host/auth/realms/realm1?.**.) for authentication.
I also in gatekeeper logs that it successfully fetches the oidc configurations. But after I hit above url following error occurs in gatekeeper logs:

```
{"level":"error","ts":1584946244.340905,"caller":"keycloak-gatekeeper/middleware.go:108","msg":"no session found in request, redirecting for authorization","error":"authentication session not found"}
{"level":"info","ts":1584946244.340992,"caller":"keycloak-gatekeeper/middleware.go:90","msg":"client  
```
Fule gatekeeper logs:
```
{"level":"info","ts":1584946156.4244683,"caller":"keycloak-gatekeeper/server.go:84","msg":"starting the service","prog":"keycloak-gatekeeper","author":"Keycloak","version":"7.0.0 (git+sha: f66e137, built: 03-09-2019)"}
{"level":"info","ts":1584946156.424621,"caller":"keycloak-gatekeeper/server.go:686","msg":"attempting to retrieve configuration discovery url","url":"http://keycloak:8080/auth/realms/Cadence","timeout":"30s"}
{"level":"info","ts":1584946156.4340553,"caller":"keycloak-gatekeeper/server.go:702","msg":"successfully retrieved openid configuration from the discovery"}
{"level":"info","ts":1584946156.4362457,"caller":"keycloak-gatekeeper/server.go:157","msg":"enabled reverse proxy mode, upstream url","url":"http://127.0.0.1:5601"}
{"level":"info","ts":1584946156.4363396,"caller":"keycloak-gatekeeper/server.go:228","msg":"using session cookies only for access and refresh tokens"}
{"level":"info","ts":1584946156.436363,"caller":"keycloak-gatekeeper/server.go:255","msg":"adding a default denial into the protected resources"}
{"level":"info","ts":1584946156.4363763,"caller":"keycloak-gatekeeper/server.go:260","msg":"protecting resource","resource":"uri: /*, methods: DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT,TRACE, required: authentication only"}
{"level":"info","ts":1584946156.4368074,"caller":"keycloak-gatekeeper/server.go:384","msg":"keycloak proxy service starting","interface":"0.0.0.0:3000"}
{"level":"error","ts":1584946244.340905,"caller":"keycloak-gatekeeper/middleware.go:108","msg":"no session found in request, redirecting for authorization","error":"authentication session not found"}
{"level":"info","ts":1584946244.340992,"caller":"keycloak-gatekeeper/middleware.go:90","msg":"client request","latency":0.000136814,"status":307,"bytes":95,"client_ip":"10.8.29.183:54714","method":"GET","path":"/"}
{"level":"error","ts":1584947395.6576178,"caller":"keycloak-gatekeeper/middleware.go:108","msg":"no session found in request, redirecting for authorization","error":"authentication session not found"}
{"level":"info","ts":1584947395.657689,"caller":"keycloak-gatekeeper/middleware.go:90","msg":"client request","latency":0.000107069,"status":307,"bytes":95,"client_ip":"10.8.29.183:33002","method":"GET","path":"/"}
```

Please help what am I doing wrong here?
